import { StyleSheet, Dimensions } from 'react-native';
import { Colors as BrandColors } from '../constants/Colors';

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFF7ED", // Root peach color to fill status bar gap
  },
  topHeader: {
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 0,
    backgroundColor: "#fff",
  },
  header: {
    paddingHorizontal: 20,
    paddingBottom: 0,
    backgroundColor: "#fff",
  },
  safeArea: {
    paddingHorizontal: 20,
    paddingBottom: 0,
    backgroundColor: "#fff",
  },
  stickySearchContainer: {
    backgroundColor: "#fff",
    paddingHorizontal: 20,
    paddingTop: 0,
    paddingBottom: 0,
    zIndex: 1100, // Increased to be above results backdrop if needed
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  headerTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 0,
    paddingVertical: 0,
  },


  avatarCircle: {
    padding: 6,
    borderRadius: 19,
    backgroundColor: BrandColors.primary,
    justifyContent: "center",
    alignItems: "center",
  },
  brandHeaderContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  brandTextContainer: {
    flex: 1,
  },
  avatarText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "700",
  },
  locationButton: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    maxWidth: "65%",
    backgroundColor: "transparent",
    paddingVertical: 0,
    paddingHorizontal: 0,
    marginBottom: 0,
  },
  deliveryAddress: {
    marginHorizontal: 6,
    fontSize: 14,
    flexShrink: 1,
    color: "#222627",
    fontWeight: "600",
  },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F9FAFB",
    paddingVertical: 6,
    paddingHorizontal: 16,
    borderRadius: 24,
    gap: 12,
    borderWidth: 1,
    borderColor: '#FED7AA',
  },

  searchInput: {
    flex: 1,
    fontSize: 15,
    color: "#111827",
    paddingVertical: 4,
  },
  clearSearchButton: {
    padding: 4,
  },
  searchDropdown: {
    position: 'absolute',
    top: 66, // Slightly lower for more breathing room
    left: 20,
    right: 20, // Align nicely with the search input
    backgroundColor: "#fff",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#F3F4F6',
    zIndex: 1001,
  },
  searchBackdrop: {
    position: 'absolute',
    top: 60,
    left: -20,
    right: -20,
    height: 2000,
    backgroundColor: 'rgba(0,0,0,0.3)',
    zIndex: 999,
  },
  searchSection: {
    paddingBottom: 12,
  },
  searchDivider: {
    height: 1,
    backgroundColor: '#F3F4F6',
    marginVertical: 4,
  },
  searchSectionLabel: {
    fontSize: 12,
    fontWeight: "800",
    color: "#9CA3AF",
    letterSpacing: 1,
    textTransform: "uppercase",
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 8,
  },
  searchResultRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 14,
    gap: 16,
  },
  searchResultImage: {
    width: 52,
    height: 52,
    borderRadius: 14,
    backgroundColor: "#F9FAFB",
  },
  searchResultInfo: {
    flex: 1,
  },
  searchResultName: {
    fontSize: 15,
    fontWeight: "700",
    color: "#111827",
    marginBottom: 2,
  },
  searchResultSub: {
    fontSize: 13,
    color: "#6B7280",
    fontWeight: '500',
  },
  searchResultPrice: {
    color: BrandColors.primary,
    fontWeight: '700',
  },
  searchEmptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
  },
  searchEmptyText: {
    fontSize: 15,
    color: "#9CA3AF",
    textAlign: "center",
    marginTop: 12,
    fontWeight: '500',
  },
  searchViewAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 18,
    backgroundColor: '#FFF1F2',
    gap: 8,
    borderTopWidth: 1,
    borderTopColor: '#FFE4E6',
  },
  searchViewAllText: {
    fontSize: 15,
    fontWeight: '800',
    color: BrandColors.primary,
  },
  floatingCartButton: {
    position: "absolute",
    bottom: 50,
    right: 20,
    backgroundColor: BrandColors.primary,
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: '#EEE7D6',
    zIndex: 999,
  },
  offersContainer: {
  },
  offerCard: {
    marginHorizontal: 20,
    height: width * 0.55,
    minHeight: 180,
    maxHeight: 240,
    borderRadius: 24,
    padding: width * 0.05,
    flexDirection: "row",
    overflow: "hidden",
    position: 'relative',
  },
  offerContent: {
    flex: 1.2,
    justifyContent: "center",
    zIndex: 2,
  },
  badgeContainer: {
    position: 'absolute',
    top: 16,
    right: 16,
    zIndex: 10,
  },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(180, 83, 9, 0.5)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    gap: 6,
  },
  badgeText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
  },
  offerTitle: {
    fontSize: width > 400 ? 32 : 26,
    fontWeight: "900",
    color: "#fff",
    // @ts-ignore
    textShadow: "0px 1px 2px rgba(0, 0, 0, 0.3)",
    marginBottom: 4,
  },
  offerDescription: {
    fontSize: width > 400 ? 16 : 13,
    color: "#fff",
    marginBottom: width > 400 ? 20 : 12,
    fontWeight: '500',
    opacity: 0.95,
  },
  orderNowButton: {
    backgroundColor: "#fff",
    paddingHorizontal: width > 400 ? 24 : 18,
    paddingVertical: width > 400 ? 8 : 6,
    borderRadius: 50,
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: '#EEE7D6',
  },
  orderNowText: {
    color: BrandColors.primary,
    fontWeight: "700",
    fontSize: width > 400 ? 14 : 12,
  },
  offerImageWrapper: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'flex-end',
    position: 'absolute',
    right: -width * 0.08,
    top: 0,
    bottom: 0,
    zIndex: 1,
  },
  offerImage: {
    width: width * 0.5,
    height: '100%',
    aspectRatio: 1,
    transform: [{ rotate: '15deg' }],
  },
  section: {
    marginTop: 12,
    marginBottom: 0,
  },

  section_home: {
    marginTop: 12,
  },

  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 0,
    paddingHorizontal: 20,
  },
  sectionTitleContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 16,
  },
  sectionAccent: {
    width: 4,
    height: 24,
    backgroundColor: BrandColors.primary,
    borderRadius: 2,
    marginRight: 10,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "900",
    color: "#222627",
    letterSpacing: -0.5,
  },
  seeAllButton: {
    fontSize: 14,
    color: BrandColors.primary,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  popularDishes: {
    paddingVertical: 8,
    paddingRight: 20,
    marginBottom: 0,
  },
  modernDishCard: {
    width: 140,
    marginRight: 12,
    backgroundColor: "#fff",
    borderRadius: 20,
    overflow: 'hidden',
  },
  dishImageBg: {
    width: "100%",
    height: 110,
    backgroundColor: '#F9FAFB',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
    position: 'relative',
  },
  dishImage: {
    width: "100%",
    height: "100%",
  },
  dishQuantitySelector: {
    position: 'absolute',
    bottom: 12,
    right: 12,
    zIndex: 10,
  },
  dishCardInfo: {
    padding: 12,
  },
  dishName: {
    fontSize: 13,
    fontWeight: "500",
    color: "#292828ff",
    marginBottom: 3,
  },
  dishMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 2,
  },
  dishPrice: {
    fontSize: 13,
    fontWeight: "700",
    color: BrandColors.primary,
  },
  dishRatingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 2,
    paddingVertical: 2,
    borderRadius: 8,
  },
  dishRatingText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#D97706",
    marginLeft: 4,
  },
  dishRestaurantName: {
    fontSize: 12,
    color: "#727272ff",
    fontWeight: '500',
    flexShrink: 1,
  },
  restaurantCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    marginBottom: 24,
    marginHorizontal: 20,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#EEE7D6',
  },
  restaurantImage: {
    width: "100%",
    height: 200,
  },
  restaurantInfo: {
    padding: 16,
  },
  restaurantHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  restaurantName: {
    fontSize: 20,
    fontWeight: "900",
    color: "#222627",
    letterSpacing: -0.5,
    marginBottom: 4,
  },
  restaurantCuisine: {
    fontSize: 14,
    color: "#6B7280",
  },
  ratingContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FEF3C7",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  ratingText: {
    marginLeft: 4,
    fontSize: 14,
    fontWeight: "600",
    color: "#D97706",
  },
  metaItem: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 16,
  },
  metaText: {
    marginLeft: 4,
    fontSize: 14,
    color: "#6B7280",
  },
  // Category Filter Styles
  categoryFilterContainer: {
    paddingVertical: 16,
    backgroundColor: '#fff',
  },
  categoryPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  categoryPillActive: {
    backgroundColor: BrandColors.primary,
    borderColor: BrandColors.primary,
  },
  categoryIcon: {
    marginRight: 8,
  },
  categoryPillText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#4B5563',
  },
  categoryPillTextActive: {
    color: '#fff',
    fontWeight: '700',
  },
  noDataText: {
    textAlign: "center",
    fontSize: 16,
    color: "#6B7280",
    marginTop: 24,
  },
});