import { StyleSheet, Dimensions } from 'react-native';
import { Colors as BrandColors } from '../constants/Colors';

const { width } = Dimensions.get('window');
const FONT_SIZES = {
  xs: 11,
  sm: 12,
  md: 14,
  lg: 16,
  xl: 20,
} as const;
const SPACING = {
  xs: 6,
  sm: 8,
  md: 12,
  lg: 16,
} as const;

export const modalStyles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.42)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 20,
  },
  modalContainer: {
    width: '96%',
    maxWidth: 560,
    maxHeight: '92%',
    backgroundColor: '#fff',
    borderRadius: 28,
    padding: 20,
    paddingTop: 24,
  },
  scrollContent: {
    paddingBottom: 24,
  },
  closeButton: {
    position: 'absolute',
    top: 18,
    right: 18,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: SPACING.md,
    paddingRight: 42,
  },
  headerIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#FFF4EF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  modalTitle: {
    fontSize: FONT_SIZES.xl,
    fontWeight: '800',
    color: '#111827',
    marginBottom: 2,
  },
  modalSubtitle: {
    fontSize: FONT_SIZES.md,
    color: '#6B7280',
  },
  sectionHeader: {
    fontSize: FONT_SIZES.sm,
    fontWeight: '700',
    color: '#6B7280',
    marginBottom: SPACING.sm,
    marginTop: SPACING.md,
    letterSpacing: 0,
  },
  quickSelectContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: SPACING.xs,
  },
  quickSelectChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  quickSelectChipActive: {
    borderColor: BrandColors.primary,
    backgroundColor: '#FFF4EF',
  },
  quickSelectChipText: {
    fontSize: FONT_SIZES.sm,
    color: '#374151',
    fontWeight: '600',
    marginLeft: 6,
  },
  quickSelectChipTextActive: {
    color: BrandColors.primary,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 14,
    paddingHorizontal: 16,
    marginBottom: SPACING.sm,
    height: 58,
    backgroundColor: '#FFFFFF',
  },
  inputError: {
    borderColor: '#EF4444',
  },
  inputIcon: {
    marginRight: 12,
  },
  inputWrapper: {
    flex: 1,
    height: '100%',
    justifyContent: 'center',
  },
  inputLabelText: {
    fontSize: FONT_SIZES.xs,
    color: '#6B7280',
    marginTop: 8,
    marginBottom: -2,
    fontWeight: '500',
  },
  input: {
    flex: 1,
    fontSize: FONT_SIZES.md,
    color: '#111827',
    paddingVertical: 0,
    minHeight: 24,
  },
  rowContainer: {
    flexDirection: 'row',
    gap: SPACING.sm,
  },
  flex1: {
    flex: 1,
  },
  errorText: {
    color: '#EF4444',
    fontSize: FONT_SIZES.xs,
    marginTop: -4,
    marginBottom: SPACING.sm,
    marginLeft: 4,
  },
  labelChipsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: SPACING.xs,
  },
  labelChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 10,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    flex: 1,
    minWidth: '20%',
    justifyContent: 'center',
  },
  labelChipActive: {
    borderColor: BrandColors.primary,
    backgroundColor: '#FFF0E6',
  },
  labelChipText: {
    fontSize: FONT_SIZES.sm,
    color: '#374151',
    fontWeight: '500',
    marginLeft: 6,
  },
  labelChipTextActive: {
    color: BrandColors.primary,
  },
  defaultContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: SPACING.sm,
    marginBottom: SPACING.md,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
  },
  defaultTextContainer: {
    flex: 1,
  },
  defaultText: {
    fontSize: FONT_SIZES.md,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 4,
  },
  defaultSubText: {
    fontSize: FONT_SIZES.sm,
    color: '#6B7280',
  },
  saveButton: {
    flexDirection: 'row',
    backgroundColor: BrandColors.primary,
    paddingVertical: 16,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: SPACING.sm,
    shadowColor: BrandColors.primary,
    shadowOpacity: 0.28,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
  },
  saveButtonText: {
    color: '#fff',
    fontSize: FONT_SIZES.lg,
    fontWeight: '700',
    marginLeft: 8,
  },
  cancelButton: {
    alignItems: 'center',
    paddingVertical: SPACING.sm,
  },
  cancelButtonText: {
    color: '#4B5563',
    fontSize: FONT_SIZES.md,
    fontWeight: '600',
  },
});
