import { Dimensions, StyleSheet } from 'react-native';
import { Colors as BrandColors } from '../constants/Colors';

const { width: SCREEN_WIDTH } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  header: {
    paddingHorizontal: 20,
    paddingBottom: 4,
    backgroundColor: "transparent",
    overflow: "visible",
  },
  brandHeaderContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    marginBottom: 2,
  },
  brandTextContainer: {
    flex: 1,
  },
  brandGreeting: {
    fontSize: 12,
    fontWeight: "700",
    color: "#6B7280",
    marginBottom: 4,
  },
  title: {
    fontSize: 24,
    fontWeight: "700",
    color: "#111827",
    letterSpacing: -0.5,
    lineHeight: 30,
  },
  titleUnderline: {
    height: 3,
    width: 50,
    backgroundColor: BrandColors.primary,
    marginTop: 4,
    borderRadius: 2,
  },
  headerAction: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "rgba(255,255,255,0.85)",
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.06)",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 12,
  },
  headerActionIconWrap: {
    width: 42,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
  },
  headerBadge: {
    position: "absolute",
    top: 8,
    right: 9,
    minWidth: 16,
    height: 16,
    paddingHorizontal: 4,
    borderRadius: 8,
    backgroundColor: BrandColors.primary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.92)",
  },
  headerBadgeText: {
    fontSize: 9,
    fontWeight: "900",
    color: "#fff",
    lineHeight: 11,
  },
  searchInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F9FAFB",
    borderRadius: 24,
    paddingHorizontal: 16,
    height: 48,
    marginTop: 16,
    borderWidth: 1,
    borderColor: "#FED7AA",
    gap: 12,
  },
  cuisineItemsScroll: {
    paddingLeft: 20,
    paddingBottom: 4,
  },
  searchIcon: {
    marginRight: 0,
  },
  clearIcon: {
    padding: 4,
  },
  searchInput: {
    flex: 1,
    height: "100%",
    fontSize: 13,
    color: "#111827",
    paddingVertical: 0,
  },
  scrollContent: {
    paddingTop: 16,
  },
  sectionTight: {
    marginTop: 12,
    marginBottom: 4,
  },
  discoveryTopSection: {
    marginTop: 18,
  },
  rowHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    marginBottom: 10,
  },
  rowHeaderTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#111827",
  },
  rowHeaderLink: {
    fontSize: 13,
    fontWeight: "700",
    color: BrandColors.primary,
  },
  viewAllBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: "rgba(252, 90, 35, 0.10)",
    borderWidth: 1,
    borderColor: "rgba(252, 90, 35, 0.18)",
  },
  viewAllBtnText: {
    fontSize: 13,
    fontWeight: "800",
    color: BrandColors.primary,
  },
  chipsRow: {
    paddingHorizontal: 20,
    paddingBottom: 4,
    gap: 10,
  },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    marginRight: 10,
  },
  chipText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#374151",
  },
  section: {
    marginTop: 18,
    marginBottom: 8,
  },
  sectionCompactTop: {
    marginTop: 10,
  },
  sectionEmpty: {
    marginTop: 12,
    marginBottom: 0,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
    paddingHorizontal: 20,
  },
  sectionTitleContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 16,
  },
  sectionAccent: {
    width: 4,
    height: 24,
    backgroundColor: BrandColors.primary,
    borderRadius: 2,
    marginRight: 10,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: "#222627",
    letterSpacing: -0.5,
  },
  recentSearches: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 20,
  },
  recentSearchItem: {
    backgroundColor: "#F3F4F6",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 50,
    marginRight: 8,
    marginBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    maxWidth: SCREEN_WIDTH - 60,
  },
  recentSearchText: {
    color: "#4B5563",
    fontSize: 13,
    fontWeight: '500',
    maxWidth: SCREEN_WIDTH - 120,
  },
  noRecentSearches: {
    paddingHorizontal: 20,
    fontSize: 14,
    color: "#9CA3AF",
    textAlign: "left",
    marginBottom: 8,
  },
  cuisineSection: {
    marginTop: 14,
    marginBottom: 0,
  },
  cuisineName: {
    fontSize: 16,
    fontWeight: "800",
    color: "#4B5563",
    marginBottom: 12,
    paddingHorizontal: 20,
    letterSpacing: 0.5,
  },
  restaurantsGrid: {
    paddingHorizontal: 20,
  },
  modernRestaurantCard: {
    height: 200,
    // nearly full width card, keep a small peek
    width: Math.min(SCREEN_WIDTH - 40, 380),
    borderRadius: 16,
    marginBottom: 12,
    marginRight: 16,
    backgroundColor: '#000',
    overflow: 'hidden',
    elevation: 0,
    borderWidth: 1,
    borderColor: '#EEE7D6',
  },
  modernRestaurantImage: {
    width: '100%',
    height: '100%',
    position: 'absolute',
  },
  cardGradient: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: '60%',
  },
  modernCardContent: {
    flex: 1,
    justifyContent: 'flex-end',
    padding: 16,
  },
  cardTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  modernRestaurantName: {
    fontSize: 20,
    fontWeight: '800',
    color: '#FFF',
    flex: 1,
    marginRight: 10,
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  modernRatingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(252, 90, 35, 0.9)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  modernRatingText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 14,
    marginLeft: 4,
  },
  cardBottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modernRestaurantCuisine: {
    color: 'rgba(255, 255, 255, 0.9)',
    fontSize: 14,
    fontWeight: '600',
  },
  modernDeliveryInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  modernDeliveryText: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  horizontalScrollPadding: {
    paddingLeft: 20, // 20px
    paddingRight: 4,
  },
  menuItemCard: {
    width: 140,
    backgroundColor: "#fff",
    borderRadius: 16,
    marginRight: 12,
    borderWidth: 1,
    borderColor: '#EEE7D6',
    overflow: 'hidden',
  },
  menuItemCardGrid: {
    width: "48%",
    marginRight: 0,
    marginBottom: 12,
  },
  recommendedGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    paddingHorizontal: 20,
  },
  imageContainer: {
    width: '100%',
    aspectRatio: 1,
    overflow: 'hidden',
    backgroundColor: '#F3F4F6',
    position: 'relative',
  },
  menuItemQuantitySelector: {
    position: 'absolute',
    bottom: 6,
    right: 6,
    zIndex: 20,
  },
  menuItemImage: {
    width: "100%",
    height: "100%",
  },
  menuItemInfo: {
    padding: 12,
  },
  menuItemName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1F2937",
    marginBottom: 4,
    lineHeight: 20,
    height: 40, // Fixed height for 2 lines
  },
  menuItemMeta: {
    fontSize: 12,
    color: "#6B7280",
    fontWeight: "600",
    marginBottom: 6,
  },
  menuItemPrice: {
    fontSize: 15,
    fontWeight: "bold",
    color: BrandColors.primary,
  },
  loader: {
    marginTop: 20,
  },
  noCuisinesText: {
    fontSize: 15,
    color: "#666",
    textAlign: "center",
    marginTop: 10,
  },
  searchEmptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 100,
    paddingBottom: 40,
  },
  searchEmptyText: {
    fontSize: 16,
    color: "#9CA3AF",
    marginTop: 16,
    fontWeight: '600',
  },

  recentSearchesSection: {
    paddingHorizontal: 20,
    marginTop: 24,
    marginBottom: 16,
  },
  recentSearchesHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  recentSearchesTitleContainer: {
    flex: 1,
  },
  recentSearchesTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#111827',
  },
  recentSearchesSubtitle: {
    fontSize: 13,
    color: '#6B7280',
    marginTop: 2,
    fontWeight: '500',
  },
  clearAllButton: {
    borderWidth: 1,
    borderColor: BrandColors.primary,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 5,
    backgroundColor: '#fff',
  },
  clearAllText: {
    fontSize: 12,
    fontWeight: '700',
    color: BrandColors.primary,
  },
  recentSearchesList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 8,
  },
  recentSearchListContent: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 24,
    paddingLeft: 12,
    paddingRight: 8,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  recentSearchTextButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  recentSearchListText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
    marginRight: 6,
  },
  removeRecentSearchButton: {
    padding: 4,
    borderRadius: 10,
  },

  // Trending Searches Card
  trendingCard: {
    backgroundColor: '#FFF8F6',
    borderRadius: 24,
    padding: 20,
    marginHorizontal: 20,
    marginTop: 12,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#FFE4E1',
  },
  trendingHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  trendingIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFEBE7',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  trendingTitleContainer: {
    flex: 1,
  },
  trendingTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#111827',
  },
  trendingSubtitle: {
    fontSize: 12,
    color: '#8C7A76',
    marginTop: 1,
    fontWeight: '500',
  },
  trendingChipsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  trendingChip: {
    backgroundColor: '#fff',
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#FEE5DD',
  },
  trendingChipText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#4A3B37',
  },
});
