export interface CountryConfig {
    code: string;
    name: string;
    currencyCode: string;
}

export const COUNTRIES: CountryConfig[] = [
    { code: "US", name: "United States", currencyCode: "USD" },
    { code: "PK", name: "Pakistan", currencyCode: "PKR" },
    { code: "GB", name: "United Kingdom", currencyCode: "GBP" },
    { code: "CA", name: "Canada", currencyCode: "USD" },
    { code: "AU", name: "Australia", currencyCode: "USD" },
    { code: "DE", name: "Germany", currencyCode: "EUR" },
    { code: "FR", name: "France", currencyCode: "EUR" },
    { code: "IT", name: "Italy", currencyCode: "EUR" },
    { code: "ES", name: "Spain", currencyCode: "EUR" },
    { code: "NL", name: "Netherlands", currencyCode: "EUR" },
    { code: "BE", name: "Belgium", currencyCode: "EUR" },
    { code: "AT", name: "Austria", currencyCode: "EUR" },
    { code: "CH", name: "Switzerland", currencyCode: "EUR" },
    { code: "SE", name: "Sweden", currencyCode: "EUR" },
    { code: "NO", name: "Norway", currencyCode: "EUR" },
    { code: "DK", name: "Denmark", currencyCode: "EUR" },
    { code: "FI", name: "Finland", currencyCode: "EUR" },
    { code: "IE", name: "Ireland", currencyCode: "EUR" },
    { code: "PT", name: "Portugal", currencyCode: "EUR" },
    { code: "GR", name: "Greece", currencyCode: "EUR" },
    { code: "PL", name: "Poland", currencyCode: "PLN" },
    { code: "CZ", name: "Czech Republic", currencyCode: "CZK" },
    { code: "HU", name: "Hungary", currencyCode: "HUF" },
    { code: "RO", name: "Romania", currencyCode: "RON" },
    { code: "BG", name: "Bulgaria", currencyCode: "BGN" },
    { code: "HR", name: "Croatia", currencyCode: "EUR" },
    { code: "SK", name: "Slovakia", currencyCode: "EUR" },
    { code: "SI", name: "Slovenia", currencyCode: "EUR" },
    { code: "LT", name: "Lithuania", currencyCode: "EUR" },
    { code: "LV", name: "Latvia", currencyCode: "EUR" },
    { code: "EE", name: "Estonia", currencyCode: "EUR" },
    { code: "IN", name: "India", currencyCode: "INR" },
    { code: "CN", name: "China", currencyCode: "CNY" },
    { code: "JP", name: "Japan", currencyCode: "JPY" },
    { code: "KR", name: "South Korea", currencyCode: "KRW" },
    { code: "SG", name: "Singapore", currencyCode: "SGD" },
    { code: "MY", name: "Malaysia", currencyCode: "MYR" },
    { code: "TH", name: "Thailand", currencyCode: "THB" },
    { code: "ID", name: "Indonesia", currencyCode: "IDR" },
    { code: "PH", name: "Philippines", currencyCode: "PHP" },
    { code: "VN", name: "Vietnam", currencyCode: "VND" },
    { code: "AE", name: "United Arab Emirates", currencyCode: "AED" },
    { code: "SA", name: "Saudi Arabia", currencyCode: "SAR" },
    { code: "AZ", name: "Azerbaijan", currencyCode: "AZN" },
    { code: "EG", name: "Egypt", currencyCode: "EGP" },
    { code: "ZA", name: "South Africa", currencyCode: "ZAR" },
    { code: "NG", name: "Nigeria", currencyCode: "NGN" },
    { code: "KE", name: "Kenya", currencyCode: "KES" },
    { code: "BR", name: "Brazil", currencyCode: "BRL" },
    { code: "MX", name: "Mexico", currencyCode: "MXN" },
    { code: "AR", name: "Argentina", currencyCode: "ARS" },
    { code: "CL", name: "Chile", currencyCode: "CLP" },
    { code: "CO", name: "Colombia", currencyCode: "COP" },
    { code: "PE", name: "Peru", currencyCode: "PEN" },
    { code: "NZ", name: "New Zealand", currencyCode: "NZD" },
];
